name: Deployment
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Zip
      uses: papeloto/action-zip@v1
      with:
        files: lib/
        dest: release.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: release.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}